version: '3.8'

services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3001:3000"
  #   env_file:
  #     - .env
  #   volumes:
  #     - .:/usr/src/app
  #   depends_on:
  #     - mongo
  #   command: air ./cmd/main.go -b 0.0.0.0
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27100:27017'
    volumes:
      - ./data/dev/mongo:/data/db
